server:
  port: 8001   
  
  
spring:
  application:
    name: cloud-pay-service
    
    #  链路监控
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.5 # 采样值介于0~1 之间   1 为全部
      
      
  datasource:
    #  当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
#    driver-class-name: com.mysql.cj.jdbc.Driver 
    driver-class-name: com.mysql.jdbc.Driver    # mysql 驱动包
    url: jdbc:mysql://localhost:3306/zhsl?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8               
    username: root
    password: root
  mvc: 
    static-path-pattern: /gateway/**
  resources: 
    static-locations: file:C://gateway/
    
    
eureka:
  client:
    register-with-eureka: true # 表示将自己注册进服务中心
    fetch-registry: true # 单一中心 无所谓   服务集群 必须为true 来配合 ribbon 负载
    service-url:
      defaultZone: http://localhost:7001/eureka  
#      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka 
  instance:
    instance-id: 8001     # eureka  显示的名称
    prefer-ip-address: true    # eureka  指向显示的名称  显示ip

upload: 
   path: gateway
    
mybatis:      
    mapper-locations: classpath*:mapper/*.xml
    configuration: 
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
#    type-aliases-package: com.eiletxie.springcloud.entities
     