server:
  port: 9527  

  
spring: 
  application:
    name: cloud-gateway-gateway9527
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
#    driver-class-name: com.mysql.cj.jdbc.Driver 
    driver-class-name: com.mysql.jdbc.Driver    # mysql 驱动包
    url: jdbc:mysql://localhost:3306/zhsl?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8               
    username: root
    password: root
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAY-SERVICE
          predicates:
            - Path=/** # 断言，路径相匹配的进行路由
            - RemoteAddr=192.168.1.23 # 配置了`192.168.5.22`，其中`192.168.5.22`是客户端的`IP`地址
          filters:
          - name: Hystrix # 配置降级
            args:
              name: fallbackcmd
              fallbackUri: forward:/fallbackcontroller
                
            

#        - id: payment_route2
          #uri: http://localhost:8002
#          uri: lb://CLOUD-PAY-SERVICE
#          predicates:
#          - Path=/** #断言,路径相匹配的进行路由
#          - After=2020-03-12T15:44:15.064+08:00[Asia/Shanghai]
          #- Cookie=username,eiletxie   #带Cookie，并且username的值为eiletxie
          #- Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式
  redis: 
    host: localhost
    port: 6379
    timeout: 5000ms
    database: 1

hystrix: 
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 超过5秒不响应  直接降级
eureka:
  client:
    register-with-eureka: true #表示将自己注册进服务中心
    fetch-registry: true #单一中心 无所谓   服务集群 必须为true 来配合 ribbon 负载
    service-url:
      defaultZone: http://localhost:7001/eureka  
#      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka 
  instance:
    instance-id: gateway9527     #eureka  显示的名称
    prefer-ip-address: true    #eureka  指向显示的名称  显示ip

    
    
mybatis:      
    mapper-locations: classpath*:mapper/*.xml
#    type-aliases-package: com.eiletxie.springcloud.entities
     