server:
  port: 6001
  private:
    key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJ9d8zOCDiblFEuDa9ytgEU3iwGETVW1bWwGRfELnC0JFo5m/SS52T0IhB9Tpz54RppkpSfKDEdZ1Kp3BREITQgqAtyiVcX5Eea7+uX3vsV+NGD2kCQGDnPTk98cOpaqQiypfSJFpI/fUFRk6C3Bp9uIG/Z0G9EEx2rTe3Lirw5BAgMBAAECgYBtt2Ga4XvavTWWs1jL6cr4XD/gAHS5gBlgGIWIaMTRoIMd8Ltw0F5GDZngc1gdwvJgks+9L/X6HVczMJOVYVCeKwuBo6JcgK64lhh58wcOlMVcUSydIN4QXbUcWmPnqTsZ1xErTQSdF6ybbNbP02Kf9VL0c/2SEnFx+hlQv4ZoPQJBAM/HxXGisWmA4WMU6WSw5zN78ms85v9nAUb16eHTxEA+Gopn/0kZVdZG7DOudcC9B3h8Q+pDlZ+aY3JL0246K/cCQQDEWfD4W5xmJsr7Jf/G/i00iqMsEoaosBN8EbuyoTqGAauazqdRREv906y8Z43m+UcdyUyyvev+qya2ohDkz1mHAkBhJ5QXEm/KWU0KO1j2kBFLbYVox01r1wot2AbIZXC6aU+XsBEaaRJN41PGxqigusKnf9Nx0rA/tL0TUIlIXUL5AkEAkbima8uhkPZtYmLbJtXwurPBUa4WHg8/Bq8qe/HIOzf2IZgI+PkU5LY51kGMQMT0EJkawPTOtlxTCOvSWd3A9QJBALYU/fjwJsgA9z6/+yV60JX0TmqrS6HBP4MZ72ICDmgfrL7Fy/q+mmMWn952wxA05eqssl7mnXX0PHekdmrd9JU=
  
aes:
  private:
    key: abcdef0123456789
client:
  public:
    key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCE375QvPja/r89w54bglluNWsfDxvqwol7f3+F40TJY/WQtgLjDG7Ry7EzC4Qq4YB7dTMXXKGLar0H8buAFToeqWa8TK9gIsjacPEnnJjN5tGFmDXO7Z1Aev75S8kHbopA+KmsTYgeRXFIkaYkaC6c+60+lFfv8w4fom4L2USw0QIDAQAB
         

spring:
  application:
    name: zuul
    
  datasource: 
    url: jdbc:mysql://localhost:3306/zhsl?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

redis:
    host: localhost
    port: 6379
    timeout: 5000ms
    database: 1
    
mybatis:
  mapperLocations: classpath:mapper/*.xml   
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    #使用IP访问注册中心
    prefer-ip-address: true
    #在注册中心status的时候显示的格式，这里是 ip:端口
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname:  ${spring.cloud.client.ipAddress}

zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    api-a: 
      path: /setServiceId/**
      serviceId: cloud_consumer_order80
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 80000
    connect-timeout-millis: 80000



#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
#        isolation:
#          thread:
#            timeoutInMilliseconds: 80000
#ribbon:
#  ReadTimeout: 80000
#  ConnectTimeout: 80000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1
#  eureka:
#    enabled: true

